parser: "@typescript-eslint/parser"
env:
  browser: true
  es6: true   # Map, etc.
  mocha: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier # Removes eslint rules that conflict with prettier.
  - prettier/@typescript-eslint # Remove conflicts again.

plugins:
  - react-hooks

# Need to set this explicitly for the eslint-plugin-react.
settings:
  react:
    version: detect

rules:
  # For overloads.
  no-dupe-class-members: off

  # https://www.npmjs.com/package/eslint-plugin-react-hooks
  react-hooks/rules-of-hooks: error

  react/prop-types: off # We use Typescript to verify prop types.
