language: minimal

jobs:
  include:
    - name: Test
      script: ./ci/image/run.sh "yarn && yarn vscode && ./ci/ci.sh"
      deploy: null
    - name: Linux Release
      if: tag IS present
      script:
        - travis_wait 60 ./ci/image/run.sh "yarn && yarn vscode && ci/release.sh"
        - ./ci/release-image/push.sh
    - name: Linux ARM64 Release
      if: tag IS present
      script:
        - travis_wait 60 ./ci/image/run.sh "yarn && yarn vscode && ci/release.sh"
        - ./ci/release-image/push.sh
      arch: arm64
    - name: MacOS Release
      if: tag IS present
      os: osx
      language: node_js
      node_js: 12
      script: yarn && yarn vscode && travis_wait 60 ci/release.sh

deploy:
  - provider: releases
    edge: true
    draft: true
    tag_name: $TRAVIS_TAG
    target_commitish: $TRAVIS_COMMIT
    name: $TRAVIS_TAG
    file:
      - release/*.tar.gz
      - release/*.zip
    on:
      tags: true

cache:
  timeout: 600
  yarn: true
